### ISSUE TITLE
(node:4024) UnhandledPromiseRejectionWarning: TypeError

### ISSUE THREAD

**Issue by robot00f** [TeeSeal/coub-dl#1]
I get all this mistake.
```
C:\Users\Steam>coub-dl -i https://coub.com/view/zeb6u -o out.mp4
(node:4024) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure prop
erty `url` of 'undefined' or 'null'.
    at Function.fetch (C:\Users\Steam\node_modules\coub-dl\src\Coub.js:56:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:4024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:4024) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```

**Comment by TeeSeal** [comment]
@brunomoreno71 Yeah, that is an error it gets if there is no high resolution available for the coub. I made it fall back to medium resolution if there is no high available in the latest release 1.3.6. Update to the latest version of `coub-dl` and you should be good. 😉
