### ISSUE TITLE
install package with name coub-dl under a package

### ISSUE THREAD

**Issue by omega3** [TeeSeal/coub-dl#13]
```
npm i coub-dl
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "coub-dl" under a package
npm ERR! also called "coub-dl". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-06-27T12_38_09_327Z-debug.log

```

log:
```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'i', 'coub-dl' ]
2 info using npm@6.9.0
3 info using node@v11.15.0
4 verbose npm-session 461357d140151cc9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/coub-dl 153ms (from cache)
8 silly pacote tag manifest for coub-dl@latest fetched in 164ms
9 timing stage:loadCurrentTree Completed in 218ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 timing stage:rollbackFailedOptional Completed in 0ms
17 timing stage:runTopLevelLifecycles Completed in 225ms
18 silly saveTree coub-dl@1.5.1
19 verbose stack Error: Refusing to install package with name "coub-dl" under a package
19 verbose stack also called "coub-dl". Did you name your project the same
19 verbose stack as the dependency you're installing?
19 verbose stack
19 verbose stack For more information, see:
19 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
19 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:64:14)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
19 verbose stack     at hasMinimumFields (/usr/lib/node_modules/npm/lib/install/validate-args.js:30:12)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
19 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/validate-args.js:15:3)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose cwd /home/user/coub-dl-master
21 verbose Linux 5.0.21-1-MANJARO
22 verbose argv "/usr/bin/node" "/bin/npm" "i" "coub-dl"
23 verbose node v11.15.0
24 verbose npm  v6.9.0
25 error code ENOSELF
26 error Refusing to install package with name "coub-dl" under a package
26 error also called "coub-dl". Did you name your project the same
26 error as the dependency you're installing?
26 error
26 error For more information, see:
26 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
27 verbose exit [ 1, true ]

```

And please tell me how to start when installed as local package?

**Comment by TeeSeal** [comment]
1. It looks like you downloaded `coub-dl` as zip and then tried to install `coub-dl` into it. You cannot do that. Please check the `name` property inside `package.json`, that name cannot be the same as the one of a package you're trying to install. In short, you need to run `npm i coub-dl` in a different directory.

2. When installing as a local package people most often are aiming to use the package as a library rather than a executable. If you want to use it in the terminal it is recommended that you install the package globally so node can add the binaries to your PATH, and then you can use it with just `coub-dl ...`. But if you insist on installing it locally then you can do:
  ```
  $ npm i coub-dl
  $ npx coub-dl ...
  ```

**Comment by omega3** [comment]
Ok. It works. 

I downloaded by using git clone and without entering this downloaded folder I issued `npm i coub-dl`

Thank you for explaining.
