### ISSUE TITLE
Windows 10 CMD requires administrator access

### ISSUE THREAD

**Issue by dimm999** [TeeSeal/coub-dl#4]
Hi thx for this awesome tool!
I have problem with run it and only when I started cmd with admin rights I could download video.
Before that I had error:

`D:\>coub-dl -i https://coub.com/view/16f8uy -o out.mp4 --loop 3 -C
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by TeeSeal** [comment]
Hey,

This is not an issue with coub-dl itself. This error pops up when node cannot find ffmpeg in your PATH environment variable.

If it works when you run it as admin, and not otherwise, that means that your admin environment is different from the normal one. I'm not really keen on Windows so you will need to look into how to edit your PATH environment variable and put the path to FFmpeg in there so node can find it.

**Comment by TeeSeal** [comment]
I'll be closing this. If you have further questions you can reopen or email me.
